function getSimbol(simbol){
    switch(simbol){
        case 'а':
        case 'А':
        case 'a':
        case 'A':
            return 'a';
        case 'б':
        case 'Б':
        case 'b':
        case 'B':
            return 'b';
        case 'ц':
        case 'Ц':
        case 'c':
        case 'C':
            return 'c';
        case 'й':
        case 'Й':
        case 'y':
        case 'Y':
            return 'y';
        case 'у':
        case 'У':
        case 'и':
        case 'И':
        case 'u':
        case 'U':
            return 'u';
        case 'к':
        case 'К':
        case 'k':
        case 'K':
            return 'k';
        case 'е':
        case 'Е':
        case 'e':
        case 'E':
            return 'e';
        case 'н':
        case 'Н':
        case 'n':
        case 'N':
            return 'n';
        case 'г':
        case 'Г':
        case 'ґ':
        case 'Ґ':
        case 'g':
        case 'G':
        case 'ж':
        case 'Ж':
            return 'g';
        case 'ш':
        case 'Ш':
            return 'sh';
        case 'щ':
        case 'Щ':
            return 'shch';
        case 'x':
        case 'X':
            return 'x';
        case 'з':
        case 'З':
        case 'z':
        case 'Z':
            return 'z';
        case 'х':
        case 'Х':
        case 'h':
        case 'H':
            return 'h';
        case 'ї':
        case 'Ї':
        case 'і':
        case 'І':
        case 'i':
        case 'I':
            return 'i';
        case 'в':
        case 'В':
        case 'v':
        case 'V':
            return 'v';
        case 'п':
        case 'П':
        case 'p':
        case 'P':
            return 'p';
        case 'р':
        case 'Р':
        case 'r':
        case 'R':
            return 'r';
        case 'о':
        case 'О':
        case 'o':
        case 'O':
            return 'o';
        case 'л':
        case 'Л':
        case 'l':
        case 'L':
            return 'l';
        case 'д':
        case 'Д':
        case 'd':
        case 'D':
            return 'd';
        case 'є':
        case 'Є':
            return 'ye';
        case 'я':
        case 'Я':
            return 'ya';
        case 'ч':
        case 'Ч':
            return 'ch';
        case 'ф':
        case 'Ф':
        case 'f':
        case 'F':
            return 'f';
        case 'с':
        case 'С':
        case 's':
        case 'S':
            return 's';
        case 'м':
        case 'М':
        case 'm':
        case 'M':
            return 'm';
        case 'т':
        case 'Т':
        case 't':
        case 'T':
            return 't';
        case 'ю':
        case 'Ю':
            return 'yu';
        case 'Q':
        case 'q':
            return 'q';
        case 'w':
        case 'W':
            return 'w';
        case 'j':
        case 'J':
            return 'j';
        case '1':
            return 1;
        case '2':
            return 2;
        case '3':
            return 3;
        case '4':
            return 4;
        case '5':
            return 5;
        case '6':
            return 6;
        case '7':
            return 7;
        case '8':
            return 8;
        case '9':
            return 9;
        case '0':
            return 0;
        default:
            return '-';
    }
}
createSlug = function(str) {
    let slugString = '';
    for(let i=0; i<str.length; i++){
        slugString += getSimbol(str[i]);
    }
    return slugString;
};

module.exports = createSlug;